### ISSUE TITLE
Only install if directory doesn't exist or is empty

### ISSUE THREAD

**Issue by GeorgeHanson** [johnpbloch/wordpress-core-installer#19]
Is it possible to only have it install wordpress if the directory it is trying to install to either doesn't exist or is empty?

For example, we had an issue with one of the packages in our vendor folder and ended up removing the vendor folder. Then upon doing a ```composer install```, it removed the current wordpress installation we had, along with custom themes, plugins etc.

Thanks

**Comment by tomjn** [comment]
You can't do a root WP install with composer, it has to be a sub directory install. This is because composer doesn't do nested packages, and it updates a package by deleting it and installing the newer version in its place.

Implementing this request would make it impossible to update WP via Composer

**Comment by johnpbloch** [comment]
The other problem beyond root installations being unsupported that I see with this proposal is that if the installer won't allow using non-empty directories, it prevents composer from ever updating core. If you're not using composer to update your packages, then what's the point of using composer at all? Downloading a package and unpacking it is the least valuable part of what composer does.
