### ISSUE TITLE
Permissions are 777 for every single file and directory installed by this package

### ISSUE THREAD

**Issue by ffxluca** [johnpbloch/wordpress-core-installer#25]
They ought to be 644 for files and 755 for folders

**Comment by johnpbloch** [comment]
@ffxluca thanks for stopping by and opening the issue. Since this package only tells Composer where `wordpress-core` type packages should be installed, this isn't really an issue with the installer. The correct place to correct this issue is the build-wp repository that houses the code that builds my fork of WP. [I went ahead and ported this issue over to that repo](https://github.com/johnpbloch/build-wp/issues/4) and will address it when I have time.

Thanks again!
